const characters = [
  {
    id: 1,
    alias: "Homero",
    familia: "Simpson",
    nombre: "Homero Jay Simpson",
    genero: "Masculino",
    edad: 38,
    frases: ["¡D'oh!", "Mmm... Rosquillas", "¡Pequeño demonio!", "¡Anda la osa!", "¡Me quiero volver chango!", "A la grande le puse Cuca", "No soy un hombre de plegarias, pero si estás en el cielo... ¡SÁLVAME POR FAVOR, SUPERMAN!", "¡A lo hecho, pecho!", "Los Santos fueron una basofia, he visto basofias en mi vida pero esta basofia fue la más basofia entre las basofias.... ¡bueno, ya me voy porque me están oyendo los ñoños!"],
    img: "/imgs/1.jpg",
  },
  {
    id: 2,
    alias: "Marge",
    familia: "Simpson",
    nombre: 'Marjorie Jaqueline Bouvier Simpson',
    genero: "Femenino",
    edad: 34,
    frases: ["Hmmmm (gruñido)", "En un momento asi, solo se puede reir", "Tal vez la muerte ponga fin a tus protestas", "A veces siento que la familia me vuelve loca y quiero ¡estallar!"],
    img: "/imgs/2.jpg",
  },
  {
    id: 3,
    alias: "Bart",
    familia: "Simpson",
    nombre: "Bartolomeo Jay Simpson",
    genero: "Masculino",
    edad: 10,
    frases: ["¡Ay, caramba!", "¡De pelos!", "Yo no fui", "Cómete mis pantaloncillos", "¿Que te paso Viejo? Antes eras chevere", "¡¿Donde esta mi elefante?!", "Deprimir a un adolecente es como hacer un huevo motuleño."],
    img: "/imgs/3.jpg",
  },
  {
    id: 4,
    alias: "Lisa",
    familia: "Simpson",
    nombre: "Lisa Marie Simpson",
    genero: "Femenino",
    edad: 8,    
    frases: ["¡Un Simpson nunca se rinde!", "Si alguien me necesita, estaré en mi habitacion.", "Las personas que acusan a otras de ser gays con frecuencia encubren su propia homosexualidad latente.", "¡Usted está mal! ¡Todo el maldito sistema está mal!"],
    img: "/imgs/4.jpg",
  },
  {
    id: 5,
    alias: "Maggie",
    familia: "Simpson",
    nombre: 'Margaret Abigail Simpson',
    genero: "Femenino",
    edad: 1,
    frases: ["Chuk Chuk (sonido de chupete)", "Papi", "Perfectirijillo"],
    img: "/imgs/5.jpg",
  },
];

module.exports = characters;
